#!/bin/sh
#
# Copyright (C) 2017  Savoir-faire Linux Inc.
#	Vivien Didelot <vivien.didelot@savoirfairelinux.com>
#	Gaël Portay <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

if [ "$1" = -c ]
then
	shift
	exec /bin/sh -c "echo $1 | $0"
elif [ -n "$1" ]
then
	echo "Usage: ${0##*/} -c URL" >&2
	exit 1
fi

exec nc -NU /tmp/qurlew.socket
